Update -Xss value (#729)
## Task

Resolves: None

## Description

This mitigates the following compilation error:
```
e: org.jetbrains.kotlin.backend.common.BackendException: Backend Internal error: Exception during psi2ir
File being compiled: (672,9) in /root/_work/pulumi-kotlin/pulumi-kotlin/build/generated-src/gitlab8/com/pulumi/gitlab/kotlin/ApplicationSettingsArgs.kt
The root cause java.lang.StackOverflowError was thrown at: java.base/java.lang.ClassLoader.defineClass1(Native Method)
null: KtDotQualifiedExpression:
com.pulumi.gitlab.ApplicationSettingsArgs.builder()
            .abuseNotificationEmail(abuseNotificationEmail?.applyValue({ args0 -> args0 }))
            .adminMode(adminMode?.applyValue({ args0 -> args0 }))
            .afterSignOutPath(afterSignOutPath?.applyValue({ args0 -> args0 }))
            .afterSignUpText(afterSignUpText?.applyValue({ args0 -> args0 }))
            .akismetApiKey(akismetApiKey?.applyValue({ args0 -> args0 }))
            .akismetEnabled(akismetEnabled?.applyValue({ args0 -> args0 }))
            .allowAccountDeletion(allowAccountDeletion?.applyValue({ args0 -> args0 }))
            .allowGroupOwnersToManageLdap(allowGroupOwnersToManageLdap?.applyValue({ args0 -> args0 }))
            .allowLocalRequestsFromSystemHooks(
                allowLocalRequestsFromSystemHooks?.applyValue({ args0 ->
                    args0
                }),
            )
...
```

https://github.com/VirtuslabRnD/pulumi-kotlin/actions/runs/11459232264/job/33149512961

The error was preventing [this
release](https://github.com/VirtuslabRnD/pulumi-kotlin/pull/725).

---------

Signed-off-by: Julia Plewa <jplewa@virtuslab.com>