Fix gradle wrapper (#10)
## Task

None

## Description

Without the `gradle-wrapper.jar` file this README line:

https://github.com/VirtuslabRnD/pulumi-kotlin/blob/f2cd5e8a3708c5fe20d5980a6fdb594915a03a3a/README.md?plain=1#L12
causes the following error:
```
Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain
Caused by: java.lang.ClassNotFoundException: org.gradle.wrapper.GradleWrapperMain
```

I also removed some duplicated lines from the `.gitignore` file, which
caused the wrapper to be ignored.